### Create Student
POST http://localhost:3003/students/create
Content-Type: application/json

{
    "name": "fulano",
    "email": "fulano2@email.com",
    "phone": "99123456789",
    "age": 21,
    "neighbor": "bairro A",
    "city": "cidade B",
    "scholarity": "EFI",
    "gender": "homem",
    "lgbt": "sim",
    "trans": "nao",
    "race": "indigena",
    "suburb": "prefiroNaoResponder",
    "internet": "naoSei",
    "access": "computador",
    "receive": 0,
    "permission": 1,
    "courses": [1,2,3]
}

### Send Volunteer Data To Email
POST http://localhost:3003/volunteers/datatoemail
Content-Type: application/json

{
    "name": "Fulano"
}

### Get All Students
GET http://localhost:3003/students/all


### Get Student By Id
GET http://localhost:3003/students/profile/cfee2928-cb17-451d-b8d8-c2e59f379d38